In [142]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


In [143]:
df1 = pd.read_csv('dados_ultimos_3_dias.csv')
df1

Unnamed: 0         id      home      away  home_goals  away_goals  \
0              0  172006763  11265335  11239770         2.0         1.0   
1              1  172006766  11240527  11265336         2.0         0.0   
2              2  172006768  11265335  11259408         2.0         0.0   
3              3  172006770  11265336  11239770         2.0         4.0   
4              4  172006772  11240527  11259408         3.0         2.0   
...          ...        ...       ...       ...         ...         ...   
1385        1385  172190962  11224382  11225716         5.0         3.0   
1386        1386  172191107  11225716  11230918         3.0         3.0   
1387        1387  172168193  11227254  11235358         1.0         3.0   
1388        1388  172191014  11235358  11225716         4.0         3.0   
1389        1389  172191072  11230918  11224382         2.0         1.0   

      tot_goals  odd_over  odd_under  goals_odd  
0           3.0     1.071        7.5        2.5  
1           2.0     1.111        6.0        2.5  
2           2.0     1.166        4.5        2.5  
3           6.0     1.015       12.0        2.5  
4           5.0     1.100        6.5        2.5  
...         ...       ...        ...        ...  
1385        8.0     1.062        8.0        2.5  
1386        6.0     1.166        4.5        2.5  
1387        4.0     1.222        4.0        2.5  
1388        7.0     1.083        7.0        2.5  
1389        3.0     1.111        6.0        2.5  

[1390 rows x 10 columns]

In [144]:
df1.dropna(inplace=True)
df1.isnull().sum()

Unnamed: 0    0
id            0
home          0
away          0
home_goals    0
away_goals    0
tot_goals     0
odd_over      0
odd_under     0
goals_odd     0
dtype: int64

In [145]:
df1

Unnamed: 0         id      home      away  home_goals  away_goals  \
0              0  172006763  11265335  11239770         2.0         1.0   
1              1  172006766  11240527  11265336         2.0         0.0   
2              2  172006768  11265335  11259408         2.0         0.0   
3              3  172006770  11265336  11239770         2.0         4.0   
4              4  172006772  11240527  11259408         3.0         2.0   
...          ...        ...       ...       ...         ...         ...   
1385        1385  172190962  11224382  11225716         5.0         3.0   
1386        1386  172191107  11225716  11230918         3.0         3.0   
1387        1387  172168193  11227254  11235358         1.0         3.0   
1388        1388  172191014  11235358  11225716         4.0         3.0   
1389        1389  172191072  11230918  11224382         2.0         1.0   

      tot_goals  odd_over  odd_under  goals_odd  
0           3.0     1.071        7.5        2.5  
1           2.0     1.111        6.0        2.5  
2           2.0     1.166        4.5        2.5  
3           6.0     1.015       12.0        2.5  
4           5.0     1.100        6.5        2.5  
...         ...       ...        ...        ...  
1385        8.0     1.062        8.0        2.5  
1386        6.0     1.166        4.5        2.5  
1387        4.0     1.222        4.0        2.5  
1388        7.0     1.083        7.0        2.5  
1389        3.0     1.111        6.0        2.5  

[1390 rows x 10 columns]

In [146]:
df1.drop(columns=['Unnamed: 0','id', 'home', 'away'])
df1.columns

Index(['Unnamed: 0', 'id', 'home', 'away', 'home_goals', 'away_goals',
       'tot_goals', 'odd_over', 'odd_under', 'goals_odd'],
      dtype='object')

In [147]:
df1['res'] = (df1['tot_goals'] > df1['goals_odd']).astype(int)
df1


Unnamed: 0         id      home      away  home_goals  away_goals  \
0              0  172006763  11265335  11239770         2.0         1.0   
1              1  172006766  11240527  11265336         2.0         0.0   
2              2  172006768  11265335  11259408         2.0         0.0   
3              3  172006770  11265336  11239770         2.0         4.0   
4              4  172006772  11240527  11259408         3.0         2.0   
...          ...        ...       ...       ...         ...         ...   
1385        1385  172190962  11224382  11225716         5.0         3.0   
1386        1386  172191107  11225716  11230918         3.0         3.0   
1387        1387  172168193  11227254  11235358         1.0         3.0   
1388        1388  172191014  11235358  11225716         4.0         3.0   
1389        1389  172191072  11230918  11224382         2.0         1.0   

      tot_goals  odd_over  odd_under  goals_odd  res  
0           3.0     1.071        7.5        2.5    1  
1           2.0     1.111        6.0        2.5    0  
2           2.0     1.166        4.5        2.5    0  
3           6.0     1.015       12.0        2.5    1  
4           5.0     1.100        6.5        2.5    1  
...         ...       ...        ...        ...  ...  
1385        8.0     1.062        8.0        2.5    1  
1386        6.0     1.166        4.5        2.5    1  
1387        4.0     1.222        4.0        2.5    1  
1388        7.0     1.083        7.0        2.5    1  
1389        3.0     1.111        6.0        2.5    1  

[1390 rows x 11 columns]

In [148]:
df1['goals_odd'].unique()

array([2.5])

In [149]:
X = df1[['odd_over', 'odd_under']]
y = df1['res']

In [41]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1021    1
1022    1
1023    1
1024    1
1025    0
Name: res, Length: 1026, dtype: int64

In [150]:


# Inicializando o StandardScaler
scaler = MinMaxScaler()

# Ajustando o scaler e transformando os dados
X_standardized = scaler.fit_transform(X)

In [151]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1385    1
1386    1
1387    1
1388    1
1389    1
Name: res, Length: 1390, dtype: int64

In [152]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_standardized, y, random_state=42, test_size=0.2)

In [97]:
import smote
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)


NameError: name 'SMOTE' is not defined

In [165]:
np.unique(df1['goals_odd'], return_counts=True)

(array([2.5]), array([1390]))

In [154]:
np.unique(df1['res'], return_counts=True)

(array([0, 1]), array([ 212, 1178]))

In [155]:
from tensorflow.keras import backend as K

def focal_loss(alpha=0.25, gamma=2.0):
    def loss(y_true, y_pred):
        bce = K.binary_crossentropy(y_true, y_pred)
        p_t = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        loss = alpha * (1 - p_t) ** gamma * bce
        return K.mean(loss)
    return loss

In [156]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation='relu'),
    tf.keras.layers.Dense(50, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    
])

In [157]:
model.compile(optimizer='adam', loss=focal_loss(), metrics=['accuracy'])

In [158]:
model.fit(x_train,y_train, epochs=50, validation_data=(x_test, y_test))

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7963 - loss: 0.0367 - val_accuracy: 0.8777 - val_loss: 0.0247
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.0271 - val_accuracy: 0.8777 - val_loss: 0.0243
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8416 - loss: 0.0276 - val_accuracy: 0.8777 - val_loss: 0.0240
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.0279 - val_accuracy: 0.8777 - val_loss: 0.0239
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.0275 - val_accuracy: 0.8777 - val_loss: 0.0239
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8235 - loss: 0.0290 - val_accuracy: 0.8777 - val_loss: 0.0238
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8392 - loss: 0.0274 - val_accuracy: 0.8777 - val_loss: 0.0240
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8227 - loss: 0.0297 - val_accuracy: 0.8777 - val_loss

In [159]:
model.evaluate(x_test, y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8870 - loss: 0.0231 


[0.023952174931764603, 0.8776978254318237]

In [160]:
re = model.predict(x_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [126]:
np.unique(re < 0.53, return_counts=True)

(array([False,  True]), array([204,   2]))

In [162]:
re = (re >= 0.5)

In [163]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(pd.Series.to_numpy(y_test), re)

In [164]:
cf

array([[  5,  29],
       [  9, 235]])